name: Release LlamaEdge-Nexus

on:
  workflow_dispatch: # manual trigger release
    inputs:
      create_release:
        description: 'Create new release'
        required: true
        type: boolean
      release_version:
        description: "Version (e.g. 1.0.0)"
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        archive-name: [llama-nexus-wasm32-wasip1.tar.gz]
    steps:
      - name: Clone project
        id: checkout
        uses: actions/checkout@v3

      - name: Setup rustup
        id: rustup
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-wasip1

      - name: Build LlamaEdge-Nexus
        id: build-llama-nexus
        env:
          RUSTFLAGS: "--cfg wasmedge --cfg tokio_unstable"
        run: |
          cargo clean
          cargo build --target wasm32-wasip1 --release
          cp target/wasm32-wasip1/release/llama-nexus.wasm ./llama-nexus.wasm

      - name: Calculate checksum
        id: checksum
        run: |
          sha256sum llama-nexus.wasm > SHA256SUM
          sha256sum config.toml >> SHA256SUM
          echo "Debug info(SHA256SUM):"
          cat SHA256SUM
          tar -czf "${{ matrix.archive-name }}" SHA256SUM llama-nexus.wasm config.toml
          mkdir -p archive
          mv "${{ matrix.archive-name }}" archive/

      - name: Tag and release names
        id: tag_and_release_names
        run: |
          echo "tag_name=${{ github.event.inputs.release_version }}" >> $GITHUB_OUTPUT
          echo "release_name=LlamaEdge-Nexus ${{ github.event.inputs.release_version }}" >> $GITHUB_OUTPUT

      - name: Create Release and Upload Release Asset
        if: ${{ github.event.inputs.create_release == 'true' && github.ref == 'refs/heads/main'}}
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.tag_and_release_names.outputs.release_name }}
          tag_name: ${{ steps.tag_and_release_names.outputs.tag_name }}
          body: TODO New Release.
          draft: true
          prerelease: true
          files: |
            archive/*
